export interface MovieCrewModel {
    adult: boolean,
    backdrop_path: string,
    genre_ids: number[],
    id: number,
    original_language: string,
    original_title: string,
    overview: string,
    popularity: number,
    poster_path: string,
    release_date: Date | null,
    title: string,
    video: boolean,
    vote_average: number,
    vote_count: number,
    credit_id: string,
    department: string,
    job: string,
    media_type: "movie"
}