export interface TvCastModel {
    adult: boolean,
    backdrop_path: string | null,
    genre_ids: number[],
    id: number,
    origin_country: string[],
    original_language: string,
    original_name: string,
    overview: string,
    popularity: number,
    poster_path: string,
    first_air_date: Date | null,
    name: string,
    vote_average: number,
    vote_count: number,
    character: string,
    credit_id: string,
    episode_count: number,
    first_credit_air_date: Date | null,
    media_type: "tv"
}